// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwpmsvvrtlyzstfejwpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13cG1zdnZydGx5enN0ZmVqd3B6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyOTU2MTgsImV4cCI6MjA3Mjg3MTYxOH0.PUcKNTr3udEzVrX-nmn022pS8Gwmn0pYYCJOeNGKA3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});